{{/*
Copyright (c) 2025 Red Hat Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: fulfillment-controller
spec:
  selector:
    matchLabels:
      app: fulfillment-controller
  replicas: 0
  template:
    metadata:
      labels:
        app: fulfillment-controller
    spec:
      serviceAccountName: controller
      volumes:
      {{- if .Values.certs.caBundle.configMap }}
      - name: cas
        configMap:
          name: {{ .Values.certs.caBundle.configMap }}
      {{- end }}
      {{- if .Values.dns.secret }}
      - name: dns-secret
        secret:
          secretName: {{ .Values.dns.secret }}
      {{- end }}
      containers:
      - name: controller
        image: {{ .Values.images.service }}
        volumeMounts:
        {{- if .Values.certs.caBundle.configMap }}
        - name: cas
          mountPath: /etc/fulfillment-controller/tls/cas
        {{- end }}
        {{- if .Values.dns.secret }}
        - name: dns-secret
          mountPath: /etc/fulfillment-controller/dns
          readOnly: true
        {{- end }}
        command:
        - /usr/local/bin/fulfillment-service
        - start
        - controller
        - --log-level={{ .Values.log.level }}
        - --log-headers={{ .Values.log.headers }}
        - --log-bodies={{ .Values.log.bodies }}
        {{- if .Values.certs.caBundle.configMap }}
        - --ca-file=/etc/fulfillment-controller/tls/cas
        {{- end }}
        - --token-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - --grpc-server-network=tcp
        - --grpc-server-address=fulfillment-api:8000
        - --grpc-keep-alive=5m
        {{- if .Values.dns.server }}
        - --dns-server={{ .Values.dns.server }}
        {{- end }}
        {{- if .Values.dns.zone }}
        - --dns-zone={{ .Values.dns.zone }}
        {{- end }}
        {{- if .Values.dns.secret }}
        - --dns-key-name-file=/etc/fulfillment-controller/dns/key
        - --dns-key-secret-file=/etc/fulfillment-controller/dns/secret
        {{- end }}
